@startuml
!include ../../_style.puml

title Состояние системы на 25.09.2026, 14:45

object "<u>passenger-101 : Пассажир</u>" as passenger {
    id = "passenger-101"
    имя = "Смирнов А.А."
    телефон = "+7 900 111-22-33"
    датаРегистрации = "2026-09-01"
    зарегистрирован = true
}

object "<u>driver-57 : Водитель</u>" as driver {
    id = "driver-57"
    имя = "Петров И.И."
    телефон = "+7 900 444-55-66"
    номерЛицензии = "Л-45721"
    рейтинг = 4.9
    доступен = false
}

object "<u>car-57 : Автомобиль</u>" as car {
    номер = "А123ВС"
    модель = "Kia Rio"
}

object "<u>order-2048 : Заказ</u>" as order {
    номер = "2048"
    точкаОтправления = "ул. Ленина, 10"
    точкаНазначения = "ул. Советская, 25"
    стоимость = "1450 RUB"
    статус = ЗАВЕРШЕН
}

object "<u>trip-2048 : Поездка</u>" as trip {
    начало = "14:12"
    конец = "14:38"
    итоговаяСтоимость = "1450 RUB"
}

object "<u>route-2048 : Маршрут</u>" as route {
    расстояние = 12.4
    продолжительность = 26
}

object "<u>payment-2048 : Платёж</u>" as payment {
    номер = "PAY-2048"
    сумма = "1450 RUB"
    статус = УСПЕШЕН
}

object "<u>rating-501 : Оценка</u>" as rating {
    балл = 5
    комментарий = "Быстрая поездка"
    дата = "2026-09-25"
}

passenger -- order
driver -- trip
driver -- car

order *-- trip
trip -- route
trip -- car
trip *-- rating

order o-- payment

@enduml