@startuml

!include ../../_style.puml

class Пассажир {
    + Имя : String
    + Телефон : String
}

class Водитель {
    + Имя : String
    + Рейтинг : double
}

class Заказ {
    + Номер : String
    + Стоимость : Money
    + Статус : Статус_Заказа
}

class Автомобиль {
    + Номер : String
    + Модель : String
}

class Поездка {
    + Начало : DateTime
    + Конец : DateTime
}

enum Статус_Заказа {
    Создан
    Поиск_водителя
    Принят
    В_пути
    Завершен
    Отменен
}

Пассажир "1" -- "0..*" Заказ
Водитель "1" -- "0..*" Поездка
Автомобиль "1" -- "0..*" Поездка
Заказ "1" -- "0..1" Поездка

@enduml