@startuml
!include ../../_style.puml

title Поток объекта «Заказ»

start

:Указать точку отправления;
:Указать точку назначения;
:Рассчитать стоимость;
:Создать заказ;
:Заказ [Создан]/

:Начать поиск подходящего водителя;
:Заказ [Поиск водителя]/

:Получить подтверждение от водителя;
:Назначить водителя заказу;
:Заказ [Принят]/

:Начать поездку;
:Заказ [В пути]/

:Завершить поездку;
:Заказ [Завершен]/

:Передать информацию о завершённой поездке пассажиру;

stop
@enduml