@startuml
!include ../../_style.puml

title Процесс «Оплатить поездку»
|Пассажир|
start
:Подтвердить оплату;
|Служба такси|
:Передать данные оплаты;
|Платёжный сервис|
:Обработать оплату;
|Служба такси|
:Получить результат оплаты;
|Пассажир|
:Получить результат оплаты;
stop
@enduml