@startuml
!include ../../_style.puml

title Процесс «Заказ поездки»
|Пассажир|
start
:Указать точку отправления;
|Служба такси|
:Определить и проверить точку отправления;
if (Точка отправления корректна?) then (да)
    |Пассажир|
    :Указать точку назначения;
    |Служба такси|
    :Определить маршрут;
    |Пассажир|
    :Подтвердить заказ;
    |Служба такси|
    :Рассчитать стоимость;
    :Создать заказ;
    :Начать поиск и выбрать свободных водителей;

    while (Водитель не назначен?) is (да)
        if (Подходящий водитель найден?) then (да)
            :Предложить заказ водителю;
            |Водитель|
            :Получить предложение;
            |Служба такси|
            :Ожидать ответ водителя;
            if (Ответ получен до истечения 60 секунд?) then (да)

                |Водитель|
                if (Водитель принимает заказ?) then (да)
                    :Принять заказ;
                    |Служба такси|
                    :Назначить выбранного водителя заказу;
                    fork
                        :Передать пассажиру информацию о водителе;
                    fork again
                        :Перевести заказ в состояние «Принят»;
                    end fork
                else (нет)

                    :Отказаться от заказа;

                    |Служба такси|
                    :Продолжить поиск водителя;
                endif
            else (таймаут)

                |Служба такси|
                :Отменить заказ и уведомить пассажира;
                stop
            endif
        else (нет)
            |Пассажир|
            :Получить сообщение, что водитель не найден;
            stop
        endif
    endwhile (нет)
    stop
else (нет)
    :Сообщить пассажиру о некорректной точке отправления;
    stop
endif
@enduml