@startuml
!include ../../_style.puml
title Процесс «Заказ поездки»

|Пассажир|
start
:Указать точку отправления;
|Служба такси|
:Определить и проверить точку отправления;

if (Точка отправления корректна?) then (да)

    |Пассажир|
    :Указать точку назначения;
    |Служба такси|
    :Определить маршрут;
    |Пассажир|
    :Подтвердить заказ;
    |Служба такси|
    :Рассчитать стоимость;
    :Создать заказ;
    :Начать поиск подходящего водителя;
    :Определить область поиска;
    :Выбрать свободных водителей;

    if (Подходящий водитель найден?) then (да)

        :Предложить заказ водителю;
        |Водитель|
        :Получить предложение;
        :Принять заказ;
        |Служба такси|
        :Получить ответ водителя;
        :Назначить выбранного водителя заказу;
        fork
            :Передать пассажиру информацию о водителе;
        fork again
            :Перевести заказ в состояние «Принят»;
        end fork
        |Пассажир|
        :Получить информацию о заказе;
        stop
    else (нет)
        |Служба такси|
        :Продолжить поиск водителя;
        :Сообщить пассажиру об отсутствии назначенного водителя;

        |Пассажир|
        :Получить сообщение об отсутствии водителя;
        stop
    endif
else (нет)
    :Сообщить пассажиру о некорректной точке отправления;
    |Пассажир|
    :Указать точку отправления повторно;
    stop
endif
@enduml