@startuml
!include ../../_style.puml

title Процесс «Оценить поездку»
|Пассажир|
start
:Выбрать завершенную поездку;
:Указать оценку;
|Служба такси|
:Сохранить оценку;
|Пассажир|
:Получить подтверждение сохранения;
stop
@enduml