@startuml
!include ../../_style.puml

title Процесс «Зарегистрироваться»
|Пользователь|
start
:Выбрать тип регистрации
(Пассажир или Водитель);
:Ввести регистрационные данные;
|Служба такси|
:Проверить регистрационные данные;
:Создать учетную запись;
:Сохранить данные регистрации;
|Пользователь|
:Получить подтверждение регистрации;
stop
@enduml